### ISSUE TITLE
Add Aurora design system (Government of Canada)

### ISSUE THREAD

**Issue by s-duffey** [miukimiu/design-systems#2]
Built by the Digital Collaboration Division in the Government of Canada, Aurora is a new design system that is currently in alpha. 

Aurora is open source, multi-disciplinary and free for anyone to use. 

See the design system here: https://gctools-outilsgc.github.io/design-system-code/

**Comment by elizabetdev** [comment]
Thanks, @s-duffey! 

I've just updated the list with your suggestion: https://github.com/miukimiu/design-systems.
